import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link'
import "@/app/globals.css";
import ApolloWrapper from '../lib/ApolloProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const navItems = {
    "Home": "/",
    "Add Book": "/create",
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloWrapper>
          <div className="flex h-screen justify-center">
            <nav className="w-64 bg-gray-100 p-6 h-screen">
              <p className="text-xl bg-gray-200 text-center p-2">Actions</p>
              <ul>
                {
                  Object.entries(navItems).map(([label, path]) => (
                    <Link key={label} href={path} className="block pl-4 p-1 hover:bg-gray-200 hover:underline">{label}</Link>
                  ))
                }
              </ul>
            </nav>
            <div className="flex flex-col w-full bg-gray-200">
              <header className="shadow p-2 bg-gray-100 text-left">
              <p className="flex text-4xl justify-center">Books CRUD</p>
                  <p className="text-lg text-right font-semibold">Login | Other options</p>
                </header>
              <main className="flex-1 overflow-auto w-full bg-gray-200 text-center">
                {children}
              </main>
              <footer className="bg-white shadow p-4 text-center text-sm text-gray-600">
                  &copy; {new Date().getFullYear()} Toy App. No rights reserved.
                </footer>
            </div>
          </div>
      </ApolloWrapper>
      </body>
    </html>
  );
}
